import type { EventCardData } from "./EventCard";

export interface DemoEvent extends EventCardData {
  id: string;
  descriptionEn: string;
  descriptionAr: string;
  galleryImages?: string[];
}

export const demoEvents: DemoEvent[] = [
  // UPCOMING
  {
    id: "1",
    slug: "youth-entrepreneurship-summit-2026",
    titleEn: "Youth Entrepreneurship Summit 2026",
    titleAr: "قمة ريادة الأعمال للشباب 2026",
    summaryEn: "A two-day summit bringing together young entrepreneurs, investors, and change-makers from across the MENA region to explore opportunities in green and social entrepreneurship.",
    summaryAr: "قمة ليومين تجمع رواد الأعمال الشباب والمستثمرين وصناع التغيير من جميع أنحاء منطقة الشرق الأوسط وشمال أفريقيا لاستكشاف فرص ريادة الأعمال الخضراء والاجتماعية.",
    descriptionEn: "The Youth Entrepreneurship Summit 2026 is the premier gathering for aspiring entrepreneurs across the MENA region. Over two dynamic days, participants will engage in panel discussions, pitch competitions, networking sessions, and hands-on workshops led by industry leaders.\n\nThis year's theme focuses on 'Green Innovation & Social Impact,' exploring how young entrepreneurs can drive sustainable economic growth while addressing pressing social challenges.\n\nHighlights include:\n- Keynote speeches from successful social entrepreneurs\n- Pitch competition with $50,000 in seed funding prizes\n- Interactive workshops on business model validation\n- Networking sessions with investors and mentors\n- Exhibition space for startup showcases",
    descriptionAr: "قمة ريادة الأعمال للشباب 2026 هي التجمع الرئيسي لرواد الأعمال الطموحين في منطقة الشرق الأوسط وشمال أفريقيا. على مدى يومين مليئين بالنشاط، سيشارك المشاركون في حلقات نقاش ومسابقات عرض أفكار وجلسات تواصل وورش عمل تفاعلية يقودها قادة الصناعة.",
    imageUrl: "/images/international-professionals.jpg",
    startDate: "2026-05-15T09:00:00",
    endDate: "2026-05-16T17:00:00",
    location: "Beirut, Lebanon",
    locationAr: "بيروت، لبنان",
    category: "conference",
    registrationUrl: "https://example.com/register",
    isFeatured: true,
    galleryImages: ["/images/group-training-workshop.jpg", "/images/international-professionals.jpg", "/images/certificate-presentation.jpg"],
  },
  {
    id: "2",
    slug: "green-business-webinar-series",
    titleEn: "Green Business Webinar Series: Climate-Smart Agriculture",
    titleAr: "سلسلة ندوات الأعمال الخضراء: الزراعة الذكية مناخياً",
    summaryEn: "Online webinar exploring climate-smart agricultural practices and green business models for entrepreneurs in the agritech sector.",
    summaryAr: "ندوة إلكترونية تستكشف الممارسات الزراعية الذكية مناخياً ونماذج الأعمال الخضراء لرواد الأعمال في قطاع التكنولوجيا الزراعية.",
    descriptionEn: "Join us for an insightful webinar on climate-smart agriculture and how entrepreneurs can build profitable green businesses in the agritech sector. Our panel of experts will share practical strategies for integrating sustainability into your business model.",
    descriptionAr: "انضم إلينا في ندوة ثاقبة حول الزراعة الذكية مناخياً وكيف يمكن لرواد الأعمال بناء أعمال خضراء مربحة في قطاع التكنولوجيا الزراعية.",
    imageUrl: "/images/field-visit-rural.jpg",
    startDate: "2026-04-20T14:00:00",
    location: "Online (Zoom)",
    locationAr: "عبر الإنترنت (Zoom)",
    category: "webinar",
    registrationUrl: "https://example.com/register",
  },
  {
    id: "3",
    slug: "women-leadership-workshop-tripoli",
    titleEn: "Women in Leadership Workshop — Tripoli",
    titleAr: "ورشة القيادة النسائية — طرابلس",
    summaryEn: "Intensive 3-day workshop empowering women with leadership skills, financial literacy, and business management techniques.",
    summaryAr: "ورشة عمل مكثفة لمدة 3 أيام لتمكين النساء بمهارات القيادة ومحو الأمية المالية وتقنيات إدارة الأعمال.",
    descriptionEn: "This intensive workshop is designed for women entrepreneurs and aspiring leaders in North Lebanon. Over three days, participants will develop practical leadership skills through interactive exercises, case studies, and mentorship sessions.",
    descriptionAr: "هذه الورشة المكثفة مصممة لرائدات الأعمال والقياديات الطموحات في شمال لبنان. على مدى ثلاثة أيام، ستطور المشاركات مهارات قيادية عملية من خلال تمارين تفاعلية ودراسات حالة وجلسات إرشاد.",
    imageUrl: "/images/nawra-women-training.jpg",
    startDate: "2026-04-05T09:00:00",
    endDate: "2026-04-07T16:00:00",
    location: "Tripoli, North Lebanon",
    locationAr: "طرابلس، شمال لبنان",
    category: "workshop",
    registrationUrl: "https://example.com/register",
  },
  {
    id: "4",
    slug: "community-resilience-forum-bekaa",
    titleEn: "Community Resilience Forum — Bekaa Valley",
    titleAr: "منتدى صمود المجتمع — سهل البقاع",
    summaryEn: "Forum bringing together community leaders, NGOs, and local authorities to discuss resilience-building strategies and social cohesion initiatives.",
    summaryAr: "منتدى يجمع قادة المجتمع والمنظمات غير الحكومية والسلطات المحلية لمناقشة استراتيجيات بناء الصمود ومبادرات التماسك الاجتماعي.",
    descriptionEn: "The Community Resilience Forum is a collaborative event that brings together diverse stakeholders to share best practices in community development and resilience-building in the Bekaa Valley.",
    descriptionAr: "منتدى صمود المجتمع هو فعالية تعاونية تجمع أصحاب المصلحة المتنوعين لتبادل أفضل الممارسات في التنمية المجتمعية وبناء الصمود في سهل البقاع.",
    imageUrl: "/images/outdoor-certificate-ceremony.jpg",
    startDate: "2026-06-10T10:00:00",
    location: "Zahle, Bekaa",
    locationAr: "زحلة، البقاع",
    category: "community",
  },
  // PAST
  {
    id: "5",
    slug: "siyb-graduation-ceremony-2025",
    titleEn: "SIYB Graduation Ceremony 2025",
    titleAr: "حفل تخريج SIYB 2025",
    summaryEn: "Celebrating the graduation of 120 entrepreneurs who completed the ILO-certified Start & Improve Your Business training program.",
    summaryAr: "الاحتفال بتخريج 120 رائد أعمال أكملوا برنامج التدريب المعتمد من منظمة العمل الدولية 'ابدأ وحسّن عملك'.",
    descriptionEn: "A milestone celebration marking the graduation of 120 entrepreneurs from across Lebanon who successfully completed the ILO-certified SIYB program. The ceremony featured keynote speeches, success stories, and certificate distribution.",
    descriptionAr: "احتفال بإنجاز يمثل تخريج 120 رائد أعمال من جميع أنحاء لبنان أكملوا بنجاح برنامج SIYB المعتمد من منظمة العمل الدولية.",
    imageUrl: "/images/certificate-presentation.jpg",
    startDate: "2025-12-15T16:00:00",
    location: "Beirut, Lebanon",
    locationAr: "بيروت، لبنان",
    category: "community",
    galleryImages: ["/images/certificate-presentation.jpg", "/images/women-group-certificates.jpg", "/images/group-training-workshop.jpg"],
  },
  {
    id: "6",
    slug: "digital-marketing-bootcamp-2025",
    titleEn: "Digital Marketing Bootcamp for Social Enterprises",
    titleAr: "معسكر التسويق الرقمي للمؤسسات الاجتماعية",
    summaryEn: "Intensive 2-day bootcamp covering social media strategy, content creation, and digital branding for social enterprises.",
    summaryAr: "معسكر تدريبي مكثف لمدة يومين يغطي استراتيجية وسائل التواصل الاجتماعي وإنشاء المحتوى والعلامة التجارية الرقمية للمؤسسات الاجتماعية.",
    descriptionEn: "This hands-on bootcamp equipped social enterprises with practical digital marketing skills, covering everything from brand positioning to paid advertising and analytics.",
    descriptionAr: "زوّد هذا المعسكر التدريبي العملي المؤسسات الاجتماعية بمهارات التسويق الرقمي العملية.",
    imageUrl: "/images/training-presentation.jpg",
    startDate: "2025-10-20T09:00:00",
    endDate: "2025-10-21T17:00:00",
    location: "Beirut, Lebanon",
    locationAr: "بيروت، لبنان",
    category: "training",
  },
  {
    id: "7",
    slug: "nawra-pitch-competition-2025",
    titleEn: "NAWARA Green Ventures Pitch Competition",
    titleAr: "مسابقة عروض مشاريع نورة الخضراء",
    summaryEn: "15 women-led green startups competed for seed funding in the NAWARA program's annual pitch competition across 3 MENA countries.",
    summaryAr: "تنافست 15 شركة ناشئة خضراء بقيادة نساء على التمويل الأولي في مسابقة العروض السنوية لبرنامج نورة عبر 3 دول في المنطقة.",
    descriptionEn: "The annual NAWARA pitch competition brought together the most promising women-led green startups from Lebanon, Tunisia, and Morocco. Startups presented innovative solutions in agritech, renewable energy, and circular economy.",
    descriptionAr: "جمعت مسابقة العروض السنوية لبرنامج نورة أكثر الشركات الناشئة الخضراء الواعدة بقيادة نساء من لبنان وتونس والمغرب.",
    imageUrl: "/images/nawra-dream-to-jury.jpg",
    startDate: "2025-09-18T10:00:00",
    location: "Tunis, Tunisia",
    locationAr: "تونس",
    category: "conference",
    galleryImages: ["/images/nawra-dream-to-jury.jpg", "/images/women-empowerment-art.jpg"],
  },
  {
    id: "8",
    slug: "financial-literacy-workshop-south",
    titleEn: "Financial Literacy Workshop for Women — South Lebanon",
    titleAr: "ورشة محو الأمية المالية للنساء — جنوب لبنان",
    summaryEn: "Workshop teaching budgeting, savings, micro-lending, and financial planning skills to women entrepreneurs in South Lebanon.",
    summaryAr: "ورشة عمل لتعليم إعداد الميزانية والادخار والإقراض الصغير ومهارات التخطيط المالي لرائدات الأعمال في جنوب لبنان.",
    descriptionEn: "Participants learned practical financial skills including budgeting, savings strategies, micro-lending options, and long-term financial planning for their businesses.",
    descriptionAr: "تعلم المشاركات مهارات مالية عملية بما في ذلك إعداد الميزانية واستراتيجيات الادخار وخيارات الإقراض الصغير والتخطيط المالي طويل الأمد لأعمالهن.",
    imageUrl: "/images/handcrafted-products.jpg",
    startDate: "2025-07-12T09:00:00",
    endDate: "2025-07-13T16:00:00",
    location: "Tyre, South Lebanon",
    locationAr: "صور، جنوب لبنان",
    category: "workshop",
  },
  {
    id: "9",
    slug: "community-kitchen-launch-chouf",
    titleEn: "Community Kitchen Launch — Chouf",
    titleAr: "إطلاق المطبخ المجتمعي — الشوف",
    summaryEn: "Official launch of the community kitchen in Chouf, providing meals, job training, and psychosocial support to displaced families.",
    summaryAr: "الإطلاق الرسمي للمطبخ المجتمعي في الشوف، الذي يوفر وجبات وتدريب مهني ودعم نفسي اجتماعي للعائلات النازحة.",
    descriptionEn: "The Community Kitchen launch event celebrated a new initiative providing not just meals but also vocational training and community support in the Chouf region, partnering with GIZ and International Alert.",
    descriptionAr: "احتفل حفل إطلاق المطبخ المجتمعي بمبادرة جديدة لا توفر الوجبات فحسب بل أيضاً التدريب المهني ودعم المجتمع في منطقة الشوف.",
    imageUrl: "/images/women-group-certificates.jpg",
    startDate: "2024-11-05T11:00:00",
    location: "Chouf, Lebanon",
    locationAr: "الشوف، لبنان",
    category: "community",
  },
  {
    id: "10",
    slug: "agritech-innovation-webinar-2024",
    titleEn: "Agritech Innovation Webinar: Scaling Green Solutions",
    titleAr: "ندوة ابتكار التكنولوجيا الزراعية: توسيع الحلول الخضراء",
    summaryEn: "Virtual session exploring innovative agritech solutions for smallholder farmers and rural communities across the MENA region.",
    summaryAr: "جلسة افتراضية تستكشف حلول التكنولوجيا الزراعية المبتكرة لصغار المزارعين والمجتمعات الريفية عبر منطقة الشرق الأوسط وشمال أفريقيا.",
    descriptionEn: "This webinar featured presentations from agritech innovators and policy-makers discussing how technology can transform agriculture in post-crisis economies.",
    descriptionAr: "تضمنت هذه الندوة عروضاً من مبتكري التكنولوجيا الزراعية وصانعي السياسات حول كيفية تحويل التكنولوجيا للزراعة في الاقتصادات بعد الأزمات.",
    imageUrl: "/images/field-visit-rural.jpg",
    startDate: "2024-09-22T15:00:00",
    location: "Online (Zoom)",
    locationAr: "عبر الإنترنت (Zoom)",
    category: "webinar",
  },
  {
    id: "11",
    slug: "enable-siyb-training-launch",
    titleEn: "ENABLE SIYB Training Program Launch",
    titleAr: "إطلاق برنامج تدريب ENABLE SIYB",
    summaryEn: "Official launch of the EU & ILO-funded SIYB entrepreneurship training program across 4 Lebanese governorates.",
    summaryAr: "الإطلاق الرسمي لبرنامج تدريب ريادة الأعمال SIYB الممول من الاتحاد الأوروبي ومنظمة العمل الدولية عبر 4 محافظات لبنانية.",
    descriptionEn: "The launch event kicked off the ENABLE programme's SIYB training across Beirut, Mount Lebanon, Akkar, and South Lebanon, aiming to equip 500+ aspiring entrepreneurs with certified business skills.",
    descriptionAr: "أطلق حفل الإطلاق تدريب SIYB ضمن برنامج ENABLE عبر بيروت وجبل لبنان وعكار وجنوب لبنان، بهدف تزويد أكثر من 500 رائد أعمال طموح بمهارات أعمال معتمدة.",
    imageUrl: "/images/group-training-workshop.jpg",
    startDate: "2024-03-10T10:00:00",
    location: "Beirut, Lebanon",
    locationAr: "بيروت، لبنان",
    category: "training",
  },
  {
    id: "12",
    slug: "houla-factory-opening-ceremony",
    titleEn: "Houla Women's Green Fashion Factory Opening",
    titleAr: "افتتاح مصنع أزياء حولا الخضراء للنساء",
    summaryEn: "Grand opening of the women-led green fashion factory in South Lebanon, empowering 50+ women through sustainable production.",
    summaryAr: "الافتتاح الكبير لمصنع الأزياء الخضراء بقيادة النساء في جنوب لبنان، الذي يمكّن أكثر من 50 امرأة من خلال الإنتاج المستدام.",
    descriptionEn: "A celebratory event marking the opening of the community-led sewing factory in Houla, South Lebanon. The factory empowers over 50 women through training in e-commerce, leadership, and sustainable fashion production, supported by UNIFIL.",
    descriptionAr: "فعالية احتفالية تمثل افتتاح مصنع الخياطة المجتمعي في حولا، جنوب لبنان. يمكّن المصنع أكثر من 50 امرأة من خلال التدريب على التجارة الإلكترونية والقيادة والإنتاج المستدام للأزياء بدعم من اليونيفيل.",
    imageUrl: "/images/handcrafted-products.jpg",
    startDate: "2023-06-20T11:00:00",
    location: "Houla, South Lebanon",
    locationAr: "حولا، جنوب لبنان",
    category: "community",
    galleryImages: ["/images/handcrafted-products.jpg", "/images/nawra-women-training.jpg"],
  },
];
